[workspace]
resolver = "2"
members = [ "test-suites",
  "trading"
]

[workspace.dependencies.soroban-sdk]
version = "23.4.0"

[workspace.dependencies.soroban-fixed-point-math]
version = "1.4.0"

[workspace.dependencies.sep-40-oracle]
version = "1.3.0"

[workspace.dependencies.sep-41-token]
version = "1.3.1"

[workspace.dependencies.stellar-access]
version = "0.5.0"

[workspace.dependencies.stellar-macros]
version = "0.5.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
